### ISSUE TITLE
Upgrade to HBase 1.0 API

### ISSUE THREAD

**Issue by haifengl** [yahoo/omid#29]
Currently OMID works with HBase 0.98. Do you have plans to upgrade to hbase 1.0/1.1? Thanks!

**Comment by francisco-perez-sorrosal** [comment]
Hi Haifeng!
Yes, we'll definitely upgrade Omid to the new HBase versions in the future.
Thanks for your interest!

**Comment by daijyc** [comment]
I created a pull request to upgrade hbase to 1.1.1: https://github.com/yahoo/omid/pull/30

**Comment by haifengl** [comment]
Awesome!! Thanks a lot!

**Comment by ikatkov** [comment]
Use profile 'hbase-1' to build with HBase 1.1.1.

**Comment by haifengl** [comment]
Thanks!
